targets:
  $default:
    builders:
      json_serializable:
        options:
          checked: true
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'
