name: task_medigreif_digital_health
description: "A mobile application project for Task MEDIGREIF Digital Health GmbH, focused on delivering digital health solutions."

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0 # internationalization and localization support (dates, numbers, messages, etc.)

  cupertino_icons: ^1.0.8 # iOS-style icons
  json_annotation: ^4.9.0 # annotations used with json_serializable for model generation
  flutter_riverpod: ^2.6.1 # modern, safe, and testable state management
  go_router: ^14.8.1 # declarative routing with nested navigation support
  flutter_svg: ^2.0.17 # renders SVG files in Flutter
  get_it: ^8.0.3 # service locator for dependency injection
  http: ^1.3.0 # for making HTTP requests
  flutter_dotenv: ^5.2.1 # load environment variables from .env files
  shared_preferences: ^2.5.3 # save data in the app

dev_dependencies:
  flutter_lints: ^5.0.0 # recommended lints to enforce best practices
  build_runner: ^2.4.15 # runs code generation builders like json_serializable
  json_serializable: ^6.9.4 # generates JSON serialization logic for models
  source_gen: ^2.0.0 # utilities for building source code generators
  flutter_gen_runner: # generation of asset code

flutter_gen:
  output: lib/generated/

  integrations:
    image: true
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/moods/
    - .env
